
# Generated by Django 3.2.6 on 2021-12-18 19:33


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ("user", "0005_user_username"),

    ]

    operations = [
        migrations.CreateModel(

            name="KakaoId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.IntegerField(unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kakao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
