# Generated by Django 3.2.6 on 2021-12-27 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_secret",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
