# Generated by Django 3.2.6 on 2022-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20220101_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="leave_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="graduate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
