# Generated by Django 3.2.6 on 2022-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_friendrequest"),
        ("user", "0010_auto_20220101_2137"),
    ]

    operations = []
