# Generated by Django 3.2.6 on 2022-01-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
