# Generated by Django 3.2.6 on 2021-12-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, upload_to='user/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d/<django.db.models.fields.AutoField>/')),
            ],
        ),
    ]
