# Generated by Django 3.2.6 on 2021-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainpost',
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='user/<django.db.models.fields.related.ForeignKey>/mainpost/%Y/%m/%d/<django.db.models.fields.AutoField>/'),
        ),
    ]
