# Generated by Django 3.2.6 on 2021-12-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0005_post_likeusers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
