# Generated by Django 3.2.6 on 2021-12-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_auto_20211218_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='user/<django.db.models.fields.related.ForeignKey>/mainpost/%Y/%m/%d/<django.db.models.fields.AutoField>/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
