# Generated by Django 3.2.6 on 2021-12-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_auto_20211225_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subposts', to='newsfeed.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='user/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d/<django.db.models.fields.AutoField>/'),
        ),
    ]
