# Generated by Django 3.2.6 on 2021-12-29 03:49

from django.db import migrations, models
import newsfeed.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20211227_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to=newsfeed.models.get_directory_path),
        ),
    ]
