# Generated by Django 3.2.6 on 2021-12-30 02:41

from django.db import migrations, models
import newsfeed.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0011_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, upload_to=newsfeed.models.comment_directory_path),
        ),
    ]
