# Generated by Django 3.2.6 on 2021-12-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0013_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
