# Generated by Django 3.2.6 on 2022-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0015_auto_20220101_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
