# Generated by Django 3.2.6 on 2022-01-01 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsfeed", "0016_notice_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="senders",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
