# Generated by Django 3.2.6 on 2022-01-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0018_alter_notice_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='isChecked',
            new_name='is_checked',
        ),
    ]
