# Generated by Django 3.2.6 on 2022-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0019_rename_ischecked_notice_is_checked"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scope",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
