# Generated by Django 3.2.6 on 2022-01-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0020_post_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="scope",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
