# Generated by Django 3.2.6 on 2022-01-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0022_post_shared_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_sharing",
            field=models.BooleanField(default=False),
        ),
    ]
