# Generated by Django 3.2.6 on 2022-01-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0022_alter_notice_senders"),
        ("newsfeed", "0023_post_is_sharing"),
    ]

    operations = []
