# Generated by Django 3.2.6 on 2022-01-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0025_auto_20220115_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='count',
        ),
    ]
