# Generated by Django 3.2.6 on 2022-01-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0027_auto_20220116_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="get_notice",
            field=models.BooleanField(default=True),
        ),
    ]
