# Generated by Django 3.2.6 on 2022-01-17 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsfeed", "0028_post_get_notice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="get_notice",
        ),
        migrations.AddField(
            model_name="post",
            name="notice_off_users",
            field=models.ManyToManyField(
                blank=True, related_name="notice_off_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
