# Generated by Django 3.2.6 on 2022-01-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0030_alter_notice_created'),
        ('newsfeed', '0030_auto_20220120_0056'),
    ]

    operations = [
    ]
