# Generated by Django 3.2.6 on 2022-01-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
