# Generated by Django 3.2.6 on 2022-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
