name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: microsoft/variable-substitution@v1 
      with:
        files: './project/secrets.json'
      env:
        SECRET_KEY: django-insecure-s02t!m&zc#*5*px(9eof=cu60#yo67c3q4^8-y02k*ts5d6ayg
        KAKAO_APP_KEY: 46791c7707983d68b0d7b8e2c032fb29
        AWS_SECRET_ACCESS_KEY: sHME4mLIoMoL7COpJ+svn05dFpHfdxn2Q7UV0t/y
        AWS_ACCESS_KEY_ID: AKIAYNIYTU7NVL4V32U4
      

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
        
    - name: Setting up mysql
      run: |
        sudo /etc/init.d/mysql start
        cd /usr/bin/
        ./mysql -uroot -proot -e "create user 'admin'@'localhost' identified by 'waffleteam9';grant all privileges on test_toy_project.* to 'admin'@'localhost';"

    - name: Set dummy secret
      run: |
        cd project
    
    - name: Run Tests
      run: |
        cd project
        echo "###########################"
        echo $SECRET_KEY
        cat secrets.json
        python manage.py makemigrations
        python manage.py test --noinput
